### PR TITLE
Fix initialization

### PR DESCRIPTION
**Pull request by erpaher**
Hi!

You code without table "migration" does  initialization and save last migration number, but it does't migrations

### CODE REVIEW

**Comment by anjianshi** [comment]
Thanks for this pull request. But, when you run the `initialize.py`, it will always generate the newest version of table, so there's no need to run `ver_xxx.py`.

see this example: https://github.com/anjianshi/peewee-simple-migrate/tree/master/examples

**Comment by erpaher** [comment]
In ver_1 add column "age", but class Student already contains column "age" 
In ver_2 add column "grade", but class Student already contains column "grade" 

I has downloaded your example and add script run.py  with content

``` python
from peewee import default_database
import peewee_simple_migrate as psm

import logging
logging.basicConfig(level=logging.DEBUG)

if __name__ == '__main__':
    psm.run(default_database, '.')
```

When start run.py, output in console is(I use sqlite)

DEBUG:peewee:('SELECT name FROM sqlite_master WHERE type = ? ORDER BY name;', ('table',))
DEBUG:peewee:('BEGIN DEFERRED', None)
DEBUG:peewee:('SAVEPOINT "sdda747326a014bbb8e94fd263a2ba864";', None)
DEBUG:peewee:('CREATE TABLE "student" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "age" INTEGER NOT NULL, "grade" INTEGER NOT NULL)', [])
DEBUG:peewee:('RELEASE SAVEPOINT "sdda747326a014bbb8e94fd263a2ba864";', None)
DEBUG:peewee:('SELECT name FROM sqlite_master WHERE type = ? ORDER BY name;', ('table',))
DEBUG:peewee:('CREATE TABLE "migration" ("version" INTEGER NOT NULL PRIMARY KEY, "latest_migrate" DATETIME NOT NULL)', [])
DEBUG:peewee:('INSERT INTO "migration" ("version", "latest_migrate") VALUES (?, ?)', [2, datetime.datetime(2015, 11, 5, 12, 38, 55, 716419)])
INFO:peewee-simple-migrate:initialize complete, version 2.

There are no "AlTER TABLE student ADD COLUMN", scrips ver_*.py don't work

**Comment by anjianshi** [comment]
Sorry, my example is not complete. 
I means: 
at the begining, `Student.py` is:

``` python
class Student(Model):
    id = PrimaryKeyField()
    name = CITextField()
```

then, you want to add a column `age`, so you change `Student.py`:

``` python
class Student(Model):
    id = PrimaryKeyField()
    name = CITextField()
    age = IntegerField()
```

and create a file names `ver_1.py`:

``` python
def run(db):
    migrator = PostgresqlMigrator(db)
    migrate(
        migrator.add_column("student", "age", IntegerField())
    )
```

and then, you want to add a column `name`, so you change `Student.py` again, and create a file name `ver_2.py`,
and so on.

Whether you have howmany versions, only the newest version defined in Student.py will be used.

**Comment by anjianshi** [comment]
``` yaml
Student.py: contains newest definition of Student model
initialize.py:  create tables use the model defined in Student.py
ver_1.py: transform db tables from ver_0 to ver_1
ver_2.py: transform db tables from ver_1 to ver_2
```

If there's no `migration` table, means your database was empty, then peewee_simple_migrate will create tables use initialize.py, and you directly go to the version 2.
If the version recorded in migration was 0, peewee_simple_migrate will run ver_1.py, and then run ver_2.py.
If the version was 1, peewee_simple_migrate will run ver_2.py.
If the version was 2, there's nothing to do.

**Pull request closed without merging**
